backend:
  name: git-gateway

media_folder: "src/resources/images"
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages/clients"
    create: true
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Playlist", name: "playlist", widget: "string"}
      - {label: "Code", name: "code", widget: "string"}