backend:
  name: git-gateway
  branch: master

media_folder: "/src/resources"

collections:
  - name: "Pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Videos", name: "videos", widget: "object", fields: [{label: "Video", name: "video", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Link", name: "link", widget: "string"}]}]}