backend:
  name: git-gateway
  branch: master

media_folder: "src/resources/images"
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/hospice.md"
        label: "Hospice"
        name: "hospice"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Videos", name: "videos", widget: "object", fields: [{label: "Video", name: "video", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Link", name: "link", widget: "string"}]}]}
      - file: "src/pages/hospice.md"
        label: "Hospice"
        name: "hospice"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Videos", name: "videos", widget: "object", fields: [{label: "Video", name: "video", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Link", name: "link", widget: "string"}]}]}