backend:
  name: git-gateway
  branch: master

media_folder: "src/resources/images"
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/hospice.md"
        label: "Hospice"
        name: "hospice"
        fields:
          - {label: "Title", name: "title", widget: "string"}
      - file: "src/pages/resthome.md"
        label: "Rest Home"
        name: "resthome"
        fields:
          - {label: "Title", name: "title", widget: "string"}